### PR TITLE
Direct wm.app

### PR DESCRIPTION
**Pull request by k88hudson**

### CODE REVIEW

**Comment by k88hudson** [comment]
@thisandagain sorry had to move this PR.

@thisandagain so sorry, this is totally unreadable, but basically what i did here was:

* add webmaker to npm
* add a `before_prepare` hook https://github.com/k88hudson/webmaker-app-cordova/blob/direct-wmapp/hooks/before_prepare/copy_assets.js
* replace everything in `www` with new assets from wm.app
* added a contacts plugin: https://github.com/apache/cordova-plugin-contacts

**Comment by thisandagain** [comment]
O_O 115,000 LOC ... lol. No worries. Let's work together to get the build / plugin assets out of version control next week. You ready for R?

**Comment by k88hudson** [comment]
@thisandagain yep

**Comment by k88hudson** [comment]
@thisandagain i'll file

**Comment by thisandagain** [comment]
This is a bit hard to sift through but I'm able to install / build / test / run locally. Curious if this just completely implodes on Windows. R+

/cc @Pomax

**Pull request merged**
