### PR TITLE
Add install page and manifest [mozilla/webmaker-app#663]

### PR DESCRIPTION
**Pull request by k88hudson**
This is already in the bucket but i figured it would be better to commit the files

### CODE REVIEW

**Comment by k88hudson** [comment]
R @thisandagain?

**Comment by k88hudson** [comment]
Filed https://github.com/mozilla/webmaker-app/issues/1204 https://github.com/mozilla/webmaker-app/issues/1203

**Comment by thisandagain** [comment]
:+1: R+

**Comment by k88hudson** [comment]
Ideally I'd like to move this into the webmaker-app codebase/share UA code, but we can do this when we merge repos.

**Comment by k88hudson** [comment]
@thisandagain can you look at this again? I added a temporary string instead of a redirect since the actual install page isn't ready yet.

**Comment by thisandagain** [comment]
:shipit: Thanks @k88hudson R+

**Pull request merged**
